on: push

name: Trie Tests Go

jobs:
    Tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.21.1

            - name: Run All Tests
              working-directory: ./trie/trie-go
              run: go test -v ./...
